name: release

on:
  push:
    branches: [main]

jobs:
  get-release-mode:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      mode: ${{ steps.output-mode.outputs.mode }}
    steps:
      - uses: actions/checkout@v3

      - name: Get commit URL
        env:
          COMMITS_URL: ${{ github.event.pull_request.base.repo.commits_url }}
          SHA: ${{ github.sha }}
        run: echo "COMMIT_URL=$COMMITS_URL" | sed -e "s#{/sha}#/$SHA#" >> $GITHUB_ENV

      - name: Get first line of commit message
        run: |
          JSON_TEXT=$(curl -sSL -H "Accept: application/vnd.github+json" $COMMIT_URL)
          VERSION_STRING=$(echo "$JSON_TEXT" | jq ".commit.message" | sed -E 's/^"//' | sed -E 's/"$//')
          echo -e "$VERSION_STRING" | head -n 1 >> $GITHUB_ENV

      - name: Output mode
        id: output-mode
        run: |
          if [[ "$MESSAGE" =~ "[release major]" ]]; then
            MODE="M"
          elif [[ "$MESSAGE" =~ "[release minor]" ]]; then
            MODE="m"
          elif [[ "$MESSAGE" =~ "[release minor]" ]]; then
            MODE="p"
          else
            MODE="none"
          fi
          echo "mode=$MODE" >> $GITHUB_OUTPUT

  create-tag-and-release:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: get-release-mode
    if: needs.get-release-mode.outputs.mode != "none"
    steps:
      - uses: actions/checkout@v3

      - name: Get latest version
        env:
          REPO_NAME: ${{ github.repository }}
        run: |
          JSON_TEXT=$(curl -sSL https://api.github.com/repos/$REPO_NAME/releases/latest)
          TAG_NAME = $(echo "$JSON_TEXT" | jq ".commit.message" | sed -E 's/^"v?//' | sed -E 's/"$//')
          echo "VERSION=$TAG_NAME" >> GITHUB_ENV

      - name: Increase version
        run: |
          curl -sSL https://raw.githubusercontent.com/fmahnke/shell-semver/master/increment_version.sh > increment_version.sh
          VERSION=$(bash increment_version.sh -${{ needs.get-release-mode.outputs.mode }} $VERSION)
          echo "VERSION=v$TAG_NAME" >> GITHUB_ENV

      - name: Get commit URL
        env:
          COMMITS_URL: ${{ github.event.pull_request.base.repo.commits_url }}
          SHA: ${{ github.sha }}
        run: echo "COMMIT_URL=$COMMITS_URL" | sed -e "s#{/sha}#/$SHA#" >> $GITHUB_ENV

      - name: Get commit message
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "MESSAGE<<$EOF" >> $GITHUB_ENV
          JSON_TEXT=$(curl -sSL -H "Accept: application/vnd.github+json" $COMMIT_URL)
          VERSION_STRING=$(echo "$JSON_TEXT" | jq ".commit.message" | sed -E 's/^"//' | sed -E 's/"$//')
          echo -e "$VERSION_STRING" >> $GITHUB_ENV
          echo "$EOF" >> $GITHUB_ENV

      - name: Add tag ${{ env.VERSION }}
        uses: rickstaa/action-create-tag@v1
        id: create-tag
        with:
          tag: ${{ env.VERSION }}
          tag_exists_error: true
          commit_sha: ${{ github.sha }}
          message: ${{ env.MESSAGE }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false