on:
  push:
    tags:
      - "*"

job:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v4

      - run: gh release create ${{ github.ref }} --generate-notes
